source 'https://rubygems.org'

gem 'rails', '3.2.16'

gem 'sass-rails'
gem 'uglifier',             '2.5.3'
gem 'coffee-rails'
gem 'jquery-rails',         '3.1.2'
gem 'turbolinks',           '2.3.0'
gem 'jbuilder',             '2.1.3'
gem 'rails-html-sanitizer', '1.0.1'
gem 'sdoc', group: :doc

group :development, :test do
  gem 'sqlite3',     '1.3.9'
  gem 'spring',      '1.1.3'
end

group :production do
  gem 'pg',             '0.17.1'
  gem 'rails_12factor', '0.0.2'
end
